export const mockWallet = {
  balance: 125000.5,
  currency: 'USD',
  accountNumber: '**** **** **** 4821',
  cardType: 'Visa Business',
  lastUpdated: '2026-05-25T10:30:00Z',
  pendingAmount: 15000,
};

export const mockTransactions = [
  {
    id: 'txn_001',
    amount: 50000,
    type: 'credit',
    sender: 'Michael Rodriguez',
    senderRole: 'investor',
    receiver: 'Sarah Johnson',
    receiverRole: 'entrepreneur',
    description: 'Series A Investment — EcoTech Solutions',
    status: 'success',
    date: '2026-05-24T09:15:00Z',
    category: 'investment',
  },
  {
    id: 'txn_002',
    amount: 25000,
    type: 'credit',
    sender: 'Jennifer Lee',
    senderRole: 'investor',
    receiver: 'David Chen',
    receiverRole: 'entrepreneur',
    description: 'Seed Funding — FinLeap AI',
    status: 'success',
    date: '2026-05-22T14:30:00Z',
    category: 'investment',
  },
  {
    id: 'txn_003',
    amount: 10000,
    type: 'debit',
    sender: 'Sarah Johnson',
    senderRole: 'entrepreneur',
    receiver: 'Legal Services Inc.',
    receiverRole: 'service',
    description: 'Legal & Compliance Fees',
    status: 'success',
    date: '2026-05-21T11:00:00Z',
    category: 'expense',
  },
  {
    id: 'txn_004',
    amount: 75000,
    type: 'credit',
    sender: 'Robert Torres',
    senderRole: 'investor',
    receiver: 'Maya Patel',
    receiverRole: 'entrepreneur',
    description: 'Pre-Series A — HealthAI Platform',
    status: 'pending',
    date: '2026-05-20T16:45:00Z',
    category: 'investment',
  },
  {
    id: 'txn_005',
    amount: 5000,
    type: 'debit',
    sender: 'David Chen',
    senderRole: 'entrepreneur',
    receiver: 'Marketing Agency Pro',
    receiverRole: 'service',
    description: 'Digital Marketing Campaign',
    status: 'success',
    date: '2026-05-19T10:20:00Z',
    category: 'expense',
  },
  {
    id: 'txn_006',
    amount: 100000,
    type: 'credit',
    sender: 'Michael Rodriguez',
    senderRole: 'investor',
    receiver: 'James Wilson',
    receiverRole: 'entrepreneur',
    description: 'Series B Bridge — CloudScale',
    status: 'failed',
    date: '2026-05-18T08:00:00Z',
    category: 'investment',
  },
  {
    id: 'txn_007',
    amount: 15000,
    type: 'debit',
    sender: 'Maya Patel',
    senderRole: 'entrepreneur',
    receiver: 'AWS Cloud Services',
    receiverRole: 'service',
    description: 'Cloud Infrastructure Q2',
    status: 'pending',
    date: '2026-05-17T13:30:00Z',
    category: 'expense',
  },
  {
    id: 'txn_008',
    amount: 30000,
    type: 'credit',
    sender: 'Jennifer Lee',
    senderRole: 'investor',
    receiver: 'Sarah Johnson',
    receiverRole: 'entrepreneur',
    description: 'Follow-on Investment Round',
    status: 'success',
    date: '2026-05-16T09:00:00Z',
    category: 'investment',
  },
];

export const mockFundingFlows = [
  {
    id: 'flow_001',
    investor: {
      name: 'Michael Rodriguez',
      initials: 'MR',
      amount: 50000,
      equity: 12,
      badge: 'Lead Investor',
      color: 'from-blue-500 to-blue-700',
    },
    entrepreneur: {
      name: 'Sarah Johnson',
      startup: 'EcoTech Solutions',
      initials: 'SJ',
      industry: 'Clean Energy',
      color: 'from-emerald-500 to-emerald-700',
    },
    status: 'completed',
    date: '2026-05-24',
    progress: 100,
  },
  {
    id: 'flow_002',
    investor: {
      name: 'Jennifer Lee',
      initials: 'JL',
      amount: 25000,
      equity: 8,
      badge: 'Angel Investor',
      color: 'from-purple-500 to-purple-700',
    },
    entrepreneur: {
      name: 'David Chen',
      startup: 'FinLeap AI',
      initials: 'DC',
      industry: 'FinTech',
      color: 'from-indigo-500 to-indigo-700',
    },
    status: 'completed',
    date: '2026-05-22',
    progress: 100,
  },
  {
    id: 'flow_003',
    investor: {
      name: 'Robert Torres',
      initials: 'RT',
      amount: 75000,
      equity: 15,
      badge: 'VC Partner',
      color: 'from-orange-500 to-orange-700',
    },
    entrepreneur: {
      name: 'Maya Patel',
      startup: 'HealthAI Platform',
      initials: 'MP',
      industry: 'HealthTech',
      color: 'from-pink-500 to-pink-700',
    },
    status: 'in_progress',
    date: '2026-05-20',
    progress: 65,
  },
  {
    id: 'flow_004',
    investor: {
      name: 'Michael Rodriguez',
      initials: 'MR',
      amount: 100000,
      equity: 18,
      badge: 'Lead Investor',
      color: 'from-blue-500 to-blue-700',
    },
    entrepreneur: {
      name: 'James Wilson',
      startup: 'CloudScale',
      initials: 'JW',
      industry: 'SaaS',
      color: 'from-cyan-500 to-cyan-700',
    },
    status: 'pending',
    date: '2026-05-18',
    progress: 30,
  },
];

export const mockRecipients = [
  { id: 'u1', name: 'Sarah Johnson', startup: 'EcoTech Solutions', role: 'entrepreneur' },
  { id: 'u2', name: 'David Chen', startup: 'FinLeap AI', role: 'entrepreneur' },
  { id: 'u3', name: 'Maya Patel', startup: 'HealthAI Platform', role: 'entrepreneur' },
  { id: 'u4', name: 'James Wilson', startup: 'CloudScale', role: 'entrepreneur' },
  { id: 'u5', name: 'Michael Rodriguez', company: 'Rodriguez Capital', role: 'investor' },
  { id: 'u6', name: 'Jennifer Lee', company: 'Lee Ventures', role: 'investor' },
];
